### ISSUE TITLE
'os.homedir()' is not a function on browser version (Windows 10, Chrome)

### ISSUE THREAD

**Issue by floydpink** [sindresorhus/is-reachable#18]
Here is the stack trace that gets print out on the console:

```
Unhandled rejection (SystemJS) os.homedir is not a function
	TypeError: os.homedir is not a function
	    at Object.eval (http://localhost:9000/jspm_packages/npm/clean-stack@1.3.0/index.js:6:20)
	    at eval (http://localhost:9000/jspm_packages/npm/clean-stack@1.3.0/index.js:27:4)
	    at eval (http://localhost:9000/jspm_packages/npm/clean-stack@1.3.0/index.js:28:3)
	    at eval (<anonymous>)
	    at Object.eval (http://localhost:9000/jspm_packages/npm/clean-stack@1.3.0.js:1:123)
	    at eval (http://localhost:9000/jspm_packages/npm/clean-stack@1.3.0.js:2:4)
	    at eval (http://localhost:9000/jspm_packages/npm/clean-stack@1.3.0.js:3:3)
	    at eval (<anonymous>)
	Evaluating http://localhost:9000/jspm_packages/npm/clean-stack@1.3.0/index.js
	Evaluating http://localhost:9000/jspm_packages/npm/clean-stack@1.3.0.js
	Evaluating http://localhost:9000/jspm_packages/npm/aggregate-error@1.0.0/index.js
	Evaluating http://localhost:9000/jspm_packages/npm/aggregate-error@1.0.0.js
	Evaluating http://localhost:9000/jspm_packages/npm/p-some@1.1.0/index.js
	Evaluating http://localhost:9000/jspm_packages/npm/p-some@1.1.0.js
	Evaluating http://localhost:9000/jspm_packages/npm/p-any@1.0.0/index.js
	Evaluating http://localhost:9000/jspm_packages/npm/p-any@1.0.0.js
	Evaluating http://localhost:9000/jspm_packages/npm/is-reachable@2.3.2/browser.js
	Evaluating http://localhost:9000/jspm_packages/npm/is-reachable@2.3.2.js
	Error loading http://localhost:9000/dist/lib/network-state/index.js
```

**Comment by silverwind** [comment]
It's here: https://github.com/sindresorhus/clean-stack/blob/28fcccdbe8bfd38213613d7e6e8eb0057b23e996/index.js#L6

Not sure what do to about this. I opened https://github.com/sindresorhus/clean-stack/issues/6.
