### ISSUE TITLE
throw new Error('Invalid URL')

### ISSUE THREAD

**Issue by przemyslawpluta** [sindresorhus/is-reachable#30]
Looks like check to `fashion-bcom-prod.herokuapp.com` example url throws `Invalid URL`

```js
isReachable('fashion-bcom-prod.herokuapp.com').then(reachable => console.log(reachable)).catch(err => console.log(err));
```
Site seems to redirect to nothing `http://` gets added and entire lib throws and breaks
```bash
{ normalizeProtocol: true,
  normalizeHttps: false,
  stripFragment: true,
  stripWWW: true,
  removeQueryParameters: [ /^utm_\w+/i ],
  removeTrailingSlash: true,
  removeDirectoryIndex: false,
  sortQueryParameters: true }
--> http://fashion-bcom-prod.herokuapp.com/
{ normalizeProtocol: true,
  normalizeHttps: false,
  stripFragment: true,
  stripWWW: true,
  removeQueryParameters: [ /^utm_\w+/i ],
  removeTrailingSlash: true,
  removeDirectoryIndex: false,
  sortQueryParameters: true }
--> http://

/test/node_modules/normalize-url/index.js:66
                throw new Error('Invalid URL');
                ^

Error: Invalid URL
    at module.exports (/test/node_modules/normalize-url/index.js:66:9)
    at /test/node_modules/cacheable-request/src/index.js:43:16
    at get (/test/node_modules/got/index.js:98:20)
    at res (/test/node_modules/got/index.js:140:5)
    at ClientRequest.handler (/test/node_modules/cacheable-request/src/index.js:88:7)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:551:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
```

Also it would be better if error is returned in a fashion where it could be caught as per standard rules.

**Comment by przemyslawpluta** [comment]
#indresorhus/got#604

**Comment by przemyslawpluta** [comment]
sindresorhus/got/issues/604

**Comment by przemyslawpluta** [comment]
sindresorhus/got#604

**Comment by przemyslawpluta** [comment]
Looks like issue is linked to sindresorhus/got#604

**Comment by sindresorhus** [comment]
Latest version no longer throws.
